In [115]:
import pandas as pd
import tqdm

In [116]:
train = pd.read_csv("data_train.csv")

In [117]:
train

       loc_x  loc_y  minutes_remaining  shot_distance  shot_made_flag  shot_id
0          0      0                  7              0               1        1
1         -3    130                  9             13               0        2
2         82      8                  7              8               0        3
3        100    101                 10             14               1        4
4          0      0                  9              0               1        5
...      ...    ...                ...            ...             ...      ...
24995     97     43                  1             10               0    24996
24996     18     77                  2              7               0    24997
24997    234      4                  0             23               0    24998
24998     75     20                  2              7               0    24999
24999      0      0                  3              0               1    25000

[25000 rows x 6 columns]

In [118]:
train.describe()

,loc_x,loc_y,minutes_remaining,shot_distance,shot_made_flag,shot_id
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.00000,25000.000000
mean,7.125400,91.287880,4.885120,13.458520,0.44744,12500.500000
std,110.029921,88.289321,3.452593,9.397722,0.49724,7217.022701
min,-250.000000,-44.000000,0.000000,0.000000,0.00000,1.000000
25%,-67.250000,4.000000,2.000000,5.000000,0.00000,6250.750000
50%,0.000000,72.000000,5.000000,15.000000,0.00000,12500.500000
75%,94.000000,160.000000,8.000000,21.000000,1.00000,18750.250000
max,248.000000,791.000000,11.000000,79.000000,1.00000,25000.000000

In [119]:
import torch
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        #######Please design your model here########
        self.hidden1 = nn.Linear(2, 6)
        self.ac1 = nn.ReLU()
        self.hidden2 = nn.Linear(6, 6)
        self.ac2 = nn.ReLU()
        self.output = nn.Linear(6, 1)
        self.ac3 = nn.Sigmoid()
        
    def forward(self, x):
        #######Please design your model here########
        x = self.ac1(self.hidden1(x))
        x = self.ac2(self.hidden2(x))
        x = self.ac3(self.output(x))
        return x

In [120]:
model = MyModel()

loss_fn = nn.MSELoss()
batch_size = 32

In [121]:
opt = torch.optim.Adam(model.parameters(), lr=5e-4)

In [122]:
train_X = train[["loc_x", "loc_y"]].values
train_y = train["shot_made_flag"].values

train_X_tens = torch.Tensor(train_X)
train_y_tens = torch.Tensor(train_y).reshape(-1, 1)

In [123]:
from sklearn.model_selection import train_test_split

train_X_tens, test_X_tens, train_y_tens, test_y_tens = train_test_split(train_X_tens, train_y_tens, test_size=0.1)

In [124]:
import copy

In [125]:
import numpy as np

best_model = model
prev_acc = 0
cnt = 0

def get_acc(test_X, test_y, model):
    model.eval()
    out = model(test_X).detach().numpy()
    # print(out)
    pred = [1 if x >= 0.5 else 0 for x in out]

    # print(out)

    acc = (np.array(pred).reshape(-1) == test_y.detach().numpy().reshape(-1)).sum() / len(out)
    return acc

def train_(epoch):
    global prev_acc, best_model, cnt
    print("Epoch: ", epoch)

    loss_curr = 0;
    for i in (pt := tqdm.tqdm(range(0, len(train_X), batch_size))):
        X = train_X_tens[i:i + batch_size]
        y = train_y_tens[i:i + batch_size]


        output = model(X)
        loss = loss_fn(output, y)
        loss_curr += (loss.item())


        pt.set_postfix({"Loss": loss_curr})
        opt.zero_grad()
        loss.backward()
        opt.step()
    

    with torch.no_grad():
        acc = (get_acc(test_X_tens, test_y_tens, model=model))
        print(acc)

    if(acc > prev_acc):
        prev_acc = acc
        best_model = copy.deepcopy(model)

In [126]:
for i in range(200):
    if(train_(i) == 0): break

Epoch:  0

100%|██████████| 782/782 [00:02<00:00, 315.71it/s, Loss=nan]

0.5364
Epoch:  1

100%|██████████| 782/782 [00:02<00:00, 340.01it/s, Loss=nan]

0.5444
Epoch:  2

100%|██████████| 782/782 [00:02<00:00, 324.69it/s, Loss=nan]

0.5572
Epoch:  3

100%|██████████| 782/782 [00:02<00:00, 319.00it/s, Loss=nan]

0.5844
Epoch:  4

100%|██████████| 782/782 [00:02<00:00, 334.36it/s, Loss=nan]

0.602
Epoch:  5

100%|██████████| 782/782 [00:02<00:00, 323.07it/s, Loss=nan]

0.602
Epoch:  6

100%|██████████| 782/782 [00:02<00:00, 328.26it/s, Loss=nan]

0.602
Epoch:  7

100%|██████████| 782/782 [00:02<00:00, 330.79it/s, Loss=nan]

0.6
Epoch:  8

100%|██████████| 782/782 [00:02<00:00, 328.64it/s, Loss=nan]

0.6012
Epoch:  9

100%|██████████| 782/782 [00:02<00:00, 320.47it/s, Loss=nan]

0.6012
Epoch:  10

100%|██████████| 782/782 [00:02<00:00, 340.19it/s, Loss=nan]

0.5996
Epoch:  11

100%|██████████| 782/782 [00:02<00:00, 322.12it/s, Loss=nan]

0.6008
Epoch:  12

100%|██████████| 782/782 [00:02<00:00, 280.92it/s, Loss=nan]

0.6024
Epoch:  13

100%|██████████| 782/782 [00:02<00:00, 288.88it/s, Loss=nan]

0.6032
Epoch:  14

100%|██████████| 782/782 [00:02<00:00, 326.00it/s, Loss=nan]

0.604
Epoch:  15

100%|██████████| 782/782 [00:02<00:00, 339.80it/s, Loss=nan]

0.6032
Epoch:  16

100%|██████████| 782/782 [00:02<00:00, 338.41it/s, Loss=nan]

0.6028
Epoch:  17

100%|██████████| 782/782 [00:02<00:00, 339.71it/s, Loss=nan]

0.6036
Epoch:  18

100%|██████████| 782/782 [00:02<00:00, 347.16it/s, Loss=nan]

0.604
Epoch:  19

100%|██████████| 782/782 [00:02<00:00, 347.95it/s, Loss=nan]

0.6028
Epoch:  20

100%|██████████| 782/782 [00:02<00:00, 341.27it/s, Loss=nan]

0.604
Epoch:  21

100%|██████████| 782/782 [00:02<00:00, 343.49it/s, Loss=nan]

0.6044
Epoch:  22

100%|██████████| 782/782 [00:02<00:00, 336.20it/s, Loss=nan]

0.604
Epoch:  23

100%|██████████| 782/782 [00:02<00:00, 335.47it/s, Loss=nan]

0.6028
Epoch:  24

100%|██████████| 782/782 [00:02<00:00, 336.68it/s, Loss=nan]

0.6032
Epoch:  25

100%|██████████| 782/782 [00:02<00:00, 333.25it/s, Loss=nan]

0.6024
Epoch:  26

100%|██████████| 782/782 [00:02<00:00, 329.63it/s, Loss=nan]

0.6028
Epoch:  27

100%|██████████| 782/782 [00:02<00:00, 330.46it/s, Loss=nan]

0.6032
Epoch:  28

100%|██████████| 782/782 [00:02<00:00, 338.86it/s, Loss=nan]

0.6036
Epoch:  29

100%|██████████| 782/782 [00:02<00:00, 325.61it/s, Loss=nan]

0.6028
Epoch:  30

100%|██████████| 782/782 [00:02<00:00, 341.28it/s, Loss=nan]

0.6028
Epoch:  31

100%|██████████| 782/782 [00:02<00:00, 338.15it/s, Loss=nan]

0.6032
Epoch:  32

100%|██████████| 782/782 [00:02<00:00, 341.86it/s, Loss=nan]

0.604
Epoch:  33

100%|██████████| 782/782 [00:02<00:00, 344.98it/s, Loss=nan]

0.604
Epoch:  34

100%|██████████| 782/782 [00:02<00:00, 362.62it/s, Loss=nan]

0.604
Epoch:  35

100%|██████████| 782/782 [00:02<00:00, 345.16it/s, Loss=nan]

0.6044
Epoch:  36

100%|██████████| 782/782 [00:02<00:00, 344.08it/s, Loss=nan]

0.6052
Epoch:  37

100%|██████████| 782/782 [00:02<00:00, 340.67it/s, Loss=nan]

0.604
Epoch:  38

100%|██████████| 782/782 [00:02<00:00, 334.15it/s, Loss=nan]

0.6048
Epoch:  39

100%|██████████| 782/782 [00:02<00:00, 320.03it/s, Loss=nan]

0.6032
Epoch:  40

100%|██████████| 782/782 [00:02<00:00, 320.14it/s, Loss=nan]

0.6028
Epoch:  41

100%|██████████| 782/782 [00:02<00:00, 332.02it/s, Loss=nan]

0.6036
Epoch:  42

100%|██████████| 782/782 [00:02<00:00, 327.40it/s, Loss=nan]

0.604
Epoch:  43

100%|██████████| 782/782 [00:02<00:00, 331.81it/s, Loss=nan]

0.6036
Epoch:  44

100%|██████████| 782/782 [00:02<00:00, 321.05it/s, Loss=nan]

0.6032
Epoch:  45

100%|██████████| 782/782 [00:02<00:00, 337.50it/s, Loss=nan]

0.6028
Epoch:  46

100%|██████████| 782/782 [00:02<00:00, 350.87it/s, Loss=nan]

0.6028
Epoch:  47

100%|██████████| 782/782 [00:02<00:00, 343.72it/s, Loss=nan]

0.6024
Epoch:  48

100%|██████████| 782/782 [00:02<00:00, 344.21it/s, Loss=nan]

0.6028
Epoch:  49

100%|██████████| 782/782 [00:02<00:00, 347.69it/s, Loss=nan]

0.602
Epoch:  50

100%|██████████| 782/782 [00:02<00:00, 340.33it/s, Loss=nan]

0.6028
Epoch:  51

100%|██████████| 782/782 [00:02<00:00, 346.00it/s, Loss=nan]

0.6024
Epoch:  52

100%|██████████| 782/782 [00:02<00:00, 344.89it/s, Loss=nan]

0.6024
Epoch:  53

100%|██████████| 782/782 [00:02<00:00, 342.07it/s, Loss=nan]

0.6012
Epoch:  54

100%|██████████| 782/782 [00:02<00:00, 343.00it/s, Loss=nan]

0.6032
Epoch:  55

100%|██████████| 782/782 [00:02<00:00, 339.18it/s, Loss=nan]

0.602
Epoch:  56

100%|██████████| 782/782 [00:02<00:00, 333.89it/s, Loss=nan]

0.6008
Epoch:  57

100%|██████████| 782/782 [00:02<00:00, 319.40it/s, Loss=nan]

0.602
Epoch:  58

100%|██████████| 782/782 [00:02<00:00, 332.64it/s, Loss=nan]

0.6012
Epoch:  59

100%|██████████| 782/782 [00:02<00:00, 340.69it/s, Loss=nan]

0.6012
Epoch:  60

100%|██████████| 782/782 [00:02<00:00, 341.40it/s, Loss=nan]

0.6012
Epoch:  61

100%|██████████| 782/782 [00:02<00:00, 340.93it/s, Loss=nan]

0.6004
Epoch:  62

100%|██████████| 782/782 [00:02<00:00, 343.59it/s, Loss=nan]

0.6012
Epoch:  63

100%|██████████| 782/782 [00:02<00:00, 343.24it/s, Loss=nan]

0.6012
Epoch:  64

100%|██████████| 782/782 [00:02<00:00, 349.00it/s, Loss=nan]

0.6008
Epoch:  65

100%|██████████| 782/782 [00:02<00:00, 344.27it/s, Loss=nan]

0.6012
Epoch:  66

100%|██████████| 782/782 [00:02<00:00, 349.16it/s, Loss=nan]

0.6
Epoch:  67

100%|██████████| 782/782 [00:02<00:00, 349.29it/s, Loss=nan]

0.6008
Epoch:  68

100%|██████████| 782/782 [00:02<00:00, 358.29it/s, Loss=nan]

0.6012
Epoch:  69

100%|██████████| 782/782 [00:02<00:00, 350.35it/s, Loss=nan]

0.6
Epoch:  70

100%|██████████| 782/782 [00:02<00:00, 343.12it/s, Loss=nan]

0.6
Epoch:  71

100%|██████████| 782/782 [00:02<00:00, 343.02it/s, Loss=nan]

0.6
Epoch:  72

100%|██████████| 782/782 [00:02<00:00, 337.43it/s, Loss=nan]

0.6004
Epoch:  73

100%|██████████| 782/782 [00:02<00:00, 335.92it/s, Loss=nan]

0.5996
Epoch:  74

100%|██████████| 782/782 [00:02<00:00, 336.50it/s, Loss=nan]

0.6008
Epoch:  75

100%|██████████| 782/782 [00:02<00:00, 333.18it/s, Loss=nan]

0.6
Epoch:  76

100%|██████████| 782/782 [00:02<00:00, 340.16it/s, Loss=nan]

0.6004
Epoch:  77

100%|██████████| 782/782 [00:02<00:00, 342.38it/s, Loss=nan]

0.6
Epoch:  78

100%|██████████| 782/782 [00:02<00:00, 341.11it/s, Loss=nan]

0.6
Epoch:  79

100%|██████████| 782/782 [00:02<00:00, 343.21it/s, Loss=nan]

0.6
Epoch:  80

100%|██████████| 782/782 [00:02<00:00, 352.66it/s, Loss=nan]

0.6
Epoch:  81

100%|██████████| 782/782 [00:02<00:00, 351.64it/s, Loss=nan]

0.6
Epoch:  82

100%|██████████| 782/782 [00:02<00:00, 353.65it/s, Loss=nan]

0.6
Epoch:  83

100%|██████████| 782/782 [00:02<00:00, 354.35it/s, Loss=nan]

0.5996
Epoch:  84

100%|██████████| 782/782 [00:02<00:00, 352.60it/s, Loss=nan]

0.6004
Epoch:  85

100%|██████████| 782/782 [00:02<00:00, 349.10it/s, Loss=nan]

0.6
Epoch:  86

100%|██████████| 782/782 [00:02<00:00, 347.82it/s, Loss=nan]

0.6
Epoch:  87

100%|██████████| 782/782 [00:02<00:00, 345.05it/s, Loss=nan]

0.6
Epoch:  88

100%|██████████| 782/782 [00:02<00:00, 331.69it/s, Loss=nan]

0.6
Epoch:  89

100%|██████████| 782/782 [00:02<00:00, 335.56it/s, Loss=nan]

0.5996
Epoch:  90

100%|██████████| 782/782 [00:02<00:00, 333.09it/s, Loss=nan]

0.5996
Epoch:  91

100%|██████████| 782/782 [00:02<00:00, 334.36it/s, Loss=nan]

0.6
Epoch:  92

100%|██████████| 782/782 [00:02<00:00, 339.12it/s, Loss=nan]

0.5996
Epoch:  93

100%|██████████| 782/782 [00:02<00:00, 337.89it/s, Loss=nan]

0.5996
Epoch:  94

100%|██████████| 782/782 [00:02<00:00, 340.77it/s, Loss=nan]

0.5996
Epoch:  95

100%|██████████| 782/782 [00:02<00:00, 345.34it/s, Loss=nan]

0.5996
Epoch:  96

100%|██████████| 782/782 [00:02<00:00, 331.72it/s, Loss=nan]

0.5996
Epoch:  97

100%|██████████| 782/782 [00:02<00:00, 352.59it/s, Loss=nan]

0.6
Epoch:  98

100%|██████████| 782/782 [00:02<00:00, 357.24it/s, Loss=nan]

0.5996
Epoch:  99

100%|██████████| 782/782 [00:02<00:00, 354.58it/s, Loss=nan]

0.6
Epoch:  100

100%|██████████| 782/782 [00:02<00:00, 352.40it/s, Loss=nan]

0.5996
Epoch:  101

100%|██████████| 782/782 [00:02<00:00, 352.29it/s, Loss=nan]

0.6
Epoch:  102

100%|██████████| 782/782 [00:02<00:00, 350.31it/s, Loss=nan]

0.6004
Epoch:  103

100%|██████████| 782/782 [00:02<00:00, 341.22it/s, Loss=nan]

0.5996
Epoch:  104

100%|██████████| 782/782 [00:02<00:00, 344.50it/s, Loss=nan]

0.6
Epoch:  105

100%|██████████| 782/782 [00:02<00:00, 335.37it/s, Loss=nan]

0.6
Epoch:  106

100%|██████████| 782/782 [00:02<00:00, 333.42it/s, Loss=nan]

0.5996
Epoch:  107

100%|██████████| 782/782 [00:02<00:00, 329.15it/s, Loss=nan]

0.5996
Epoch:  108

100%|██████████| 782/782 [00:02<00:00, 339.13it/s, Loss=nan]

0.6004
Epoch:  109

100%|██████████| 782/782 [00:02<00:00, 344.89it/s, Loss=nan]

0.5996
Epoch:  110

100%|██████████| 782/782 [00:02<00:00, 338.52it/s, Loss=nan]

0.6008
Epoch:  111

100%|██████████| 782/782 [00:02<00:00, 344.82it/s, Loss=nan]

0.6
Epoch:  112

100%|██████████| 782/782 [00:02<00:00, 344.15it/s, Loss=nan]

0.6
Epoch:  113

100%|██████████| 782/782 [00:02<00:00, 349.61it/s, Loss=nan]

0.6
Epoch:  114

100%|██████████| 782/782 [00:02<00:00, 347.91it/s, Loss=nan]

0.6
Epoch:  115

100%|██████████| 782/782 [00:02<00:00, 355.12it/s, Loss=nan]

0.6
Epoch:  116

100%|██████████| 782/782 [00:02<00:00, 343.39it/s, Loss=nan]

0.6
Epoch:  117

100%|██████████| 782/782 [00:02<00:00, 349.40it/s, Loss=nan]

0.6
Epoch:  118

100%|██████████| 782/782 [00:02<00:00, 356.64it/s, Loss=nan]

0.6
Epoch:  119

100%|██████████| 782/782 [00:02<00:00, 338.11it/s, Loss=nan]

0.6
Epoch:  120

100%|██████████| 782/782 [00:02<00:00, 338.25it/s, Loss=nan]

0.6
Epoch:  121

100%|██████████| 782/782 [00:02<00:00, 334.28it/s, Loss=nan]

0.5996
Epoch:  122

100%|██████████| 782/782 [00:02<00:00, 333.64it/s, Loss=nan]

0.6
Epoch:  123

100%|██████████| 782/782 [00:02<00:00, 330.38it/s, Loss=nan]

0.6
Epoch:  124

100%|██████████| 782/782 [00:02<00:00, 337.11it/s, Loss=nan]

0.6
Epoch:  125

100%|██████████| 782/782 [00:02<00:00, 340.94it/s, Loss=nan]

0.6
Epoch:  126

100%|██████████| 782/782 [00:02<00:00, 339.48it/s, Loss=nan]

0.6
Epoch:  127

100%|██████████| 782/782 [00:02<00:00, 339.69it/s, Loss=nan]

0.6
Epoch:  128

100%|██████████| 782/782 [00:02<00:00, 345.49it/s, Loss=nan]

0.6
Epoch:  129

100%|██████████| 782/782 [00:02<00:00, 345.72it/s, Loss=nan]

0.6
Epoch:  130

100%|██████████| 782/782 [00:02<00:00, 348.16it/s, Loss=nan]

0.6
Epoch:  131

100%|██████████| 782/782 [00:02<00:00, 352.39it/s, Loss=nan]

0.6
Epoch:  132

100%|██████████| 782/782 [00:02<00:00, 349.47it/s, Loss=nan]

0.6
Epoch:  133

100%|██████████| 782/782 [00:02<00:00, 347.65it/s, Loss=nan]

0.6
Epoch:  134

100%|██████████| 782/782 [00:02<00:00, 347.69it/s, Loss=nan]

0.6
Epoch:  135

100%|██████████| 782/782 [00:02<00:00, 343.61it/s, Loss=nan]

0.6
Epoch:  136

100%|██████████| 782/782 [00:02<00:00, 342.71it/s, Loss=nan]

0.6
Epoch:  137

100%|██████████| 782/782 [00:02<00:00, 332.52it/s, Loss=nan]

0.6
Epoch:  138

100%|██████████| 782/782 [00:02<00:00, 306.28it/s, Loss=nan]

0.6
Epoch:  139

100%|██████████| 782/782 [00:02<00:00, 296.51it/s, Loss=nan]

0.6
Epoch:  140

100%|██████████| 782/782 [00:02<00:00, 294.38it/s, Loss=nan]

0.6
Epoch:  141

100%|██████████| 782/782 [00:02<00:00, 327.99it/s, Loss=nan]

0.6
Epoch:  142

100%|██████████| 782/782 [00:02<00:00, 291.31it/s, Loss=nan]

0.6
Epoch:  143

100%|██████████| 782/782 [00:02<00:00, 320.01it/s, Loss=nan]

0.6004
Epoch:  144

100%|██████████| 782/782 [00:02<00:00, 322.56it/s, Loss=nan]

0.6004
Epoch:  145

100%|██████████| 782/782 [00:02<00:00, 342.30it/s, Loss=nan]

0.6004
Epoch:  146

100%|██████████| 782/782 [00:02<00:00, 336.12it/s, Loss=nan]

0.6004
Epoch:  147

100%|██████████| 782/782 [00:02<00:00, 344.23it/s, Loss=nan]

0.6004
Epoch:  148

100%|██████████| 782/782 [00:02<00:00, 347.23it/s, Loss=nan]

0.6004
Epoch:  149

100%|██████████| 782/782 [00:02<00:00, 358.54it/s, Loss=nan]

0.6004
Epoch:  150

100%|██████████| 782/782 [00:02<00:00, 338.49it/s, Loss=nan]

0.6
Epoch:  151

100%|██████████| 782/782 [00:02<00:00, 337.65it/s, Loss=nan]

0.6
Epoch:  152

100%|██████████| 782/782 [00:02<00:00, 335.11it/s, Loss=nan]

0.6
Epoch:  153

100%|██████████| 782/782 [00:02<00:00, 330.95it/s, Loss=nan]

0.6
Epoch:  154

100%|██████████| 782/782 [00:02<00:00, 330.55it/s, Loss=nan]

0.6
Epoch:  155

100%|██████████| 782/782 [00:02<00:00, 333.74it/s, Loss=nan]

0.6004
Epoch:  156

100%|██████████| 782/782 [00:02<00:00, 334.11it/s, Loss=nan]

0.6
Epoch:  157

100%|██████████| 782/782 [00:02<00:00, 336.84it/s, Loss=nan]

0.6
Epoch:  158

100%|██████████| 782/782 [00:02<00:00, 344.74it/s, Loss=nan]

0.6004
Epoch:  159

100%|██████████| 782/782 [00:02<00:00, 344.33it/s, Loss=nan]

0.6
Epoch:  160

100%|██████████| 782/782 [00:02<00:00, 344.18it/s, Loss=nan]

0.6004
Epoch:  161

100%|██████████| 782/782 [00:02<00:00, 348.24it/s, Loss=nan]

0.6
Epoch:  162

100%|██████████| 782/782 [00:02<00:00, 352.64it/s, Loss=nan]

0.6
Epoch:  163

100%|██████████| 782/782 [00:02<00:00, 357.64it/s, Loss=nan]

0.6004
Epoch:  164

100%|██████████| 782/782 [00:02<00:00, 349.56it/s, Loss=nan]

0.6
Epoch:  165

100%|██████████| 782/782 [00:02<00:00, 341.22it/s, Loss=nan]

0.6004
Epoch:  166

100%|██████████| 782/782 [00:02<00:00, 345.03it/s, Loss=nan]

0.6004
Epoch:  167

100%|██████████| 782/782 [00:02<00:00, 337.28it/s, Loss=nan]

0.6
Epoch:  168

100%|██████████| 782/782 [00:02<00:00, 334.36it/s, Loss=nan]

0.6004
Epoch:  169

100%|██████████| 782/782 [00:02<00:00, 331.11it/s, Loss=nan]

0.6004
Epoch:  170

100%|██████████| 782/782 [00:02<00:00, 325.72it/s, Loss=nan]

0.6004
Epoch:  171

100%|██████████| 782/782 [00:02<00:00, 335.43it/s, Loss=nan]

0.6004
Epoch:  172

100%|██████████| 782/782 [00:02<00:00, 335.12it/s, Loss=nan]

0.6004
Epoch:  173

100%|██████████| 782/782 [00:02<00:00, 339.90it/s, Loss=nan]

0.6004
Epoch:  174

100%|██████████| 782/782 [00:02<00:00, 334.96it/s, Loss=nan]

0.6004
Epoch:  175

100%|██████████| 782/782 [00:02<00:00, 341.29it/s, Loss=nan]

0.6008
Epoch:  176

100%|██████████| 782/782 [00:02<00:00, 353.37it/s, Loss=nan]

0.6004
Epoch:  177

100%|██████████| 782/782 [00:02<00:00, 346.34it/s, Loss=nan]

0.6004
Epoch:  178

100%|██████████| 782/782 [00:02<00:00, 345.58it/s, Loss=nan]

0.6008
Epoch:  179

100%|██████████| 782/782 [00:02<00:00, 349.17it/s, Loss=nan]

0.6008
Epoch:  180

100%|██████████| 782/782 [00:02<00:00, 344.08it/s, Loss=nan]

0.6008
Epoch:  181

100%|██████████| 782/782 [00:02<00:00, 344.15it/s, Loss=nan]

0.6008
Epoch:  182

100%|██████████| 782/782 [00:02<00:00, 326.53it/s, Loss=nan]

0.6008
Epoch:  183

100%|██████████| 782/782 [00:02<00:00, 336.79it/s, Loss=nan]

0.6008
Epoch:  184

100%|██████████| 782/782 [00:02<00:00, 338.30it/s, Loss=nan]

0.6008
Epoch:  185

100%|██████████| 782/782 [00:02<00:00, 326.90it/s, Loss=nan]

0.6008
Epoch:  186

100%|██████████| 782/782 [00:02<00:00, 333.98it/s, Loss=nan]

0.6008
Epoch:  187

100%|██████████| 782/782 [00:02<00:00, 338.18it/s, Loss=nan]

0.6008
Epoch:  188

100%|██████████| 782/782 [00:02<00:00, 340.52it/s, Loss=nan]

0.6008
Epoch:  189

100%|██████████| 782/782 [00:02<00:00, 335.13it/s, Loss=nan]

0.6008
Epoch:  190

100%|██████████| 782/782 [00:02<00:00, 357.80it/s, Loss=nan]

0.6008
Epoch:  191

100%|██████████| 782/782 [00:02<00:00, 344.10it/s, Loss=nan]

0.6008
Epoch:  192

100%|██████████| 782/782 [00:02<00:00, 343.72it/s, Loss=nan]

0.6008
Epoch:  193

100%|██████████| 782/782 [00:02<00:00, 346.16it/s, Loss=nan]

0.6008
Epoch:  194

100%|██████████| 782/782 [00:02<00:00, 344.56it/s, Loss=nan]

0.6008
Epoch:  195

100%|██████████| 782/782 [00:02<00:00, 340.66it/s, Loss=nan]

0.6008
Epoch:  196

100%|██████████| 782/782 [00:02<00:00, 344.00it/s, Loss=nan]

0.6008
Epoch:  197

100%|██████████| 782/782 [00:02<00:00, 345.02it/s, Loss=nan]

0.6008
Epoch:  198

100%|██████████| 782/782 [00:02<00:00, 339.53it/s, Loss=nan]

0.6008
Epoch:  199

100%|██████████| 782/782 [00:02<00:00, 340.64it/s, Loss=nan]

0.6008

In [127]:
acc = (get_acc(test_X_tens, test_y_tens, model=best_model))

In [128]:
acc

0.6052

In [132]:
model_code = """  
import torch
import torch.nn as nn


class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        #######Please design your model here########
        self.hidden1 = nn.Linear(2, 6)
        self.ac1 = nn.ReLU()
        self.hidden2 = nn.Linear(6, 6)
        self.ac2 = nn.ReLU()
        self.output = nn.Linear(6, 1)
        self.ac3 = nn.Sigmoid()
        
    def forward(self, x):
        #######Please design your model here########
        x = self.ac1(self.hidden1(x))
        x = self.ac2(self.hidden2(x))
        x = self.ac3(self.output(x))
        return x


"""
# Save the model structure
with open('submission_model.py', 'w') as f:
    f.write(model_code)
print("submission_model.py file is generated.")

submission_model.py file is generated.

In [133]:
torch.save(best_model.state_dict(), 'submission_dic.pth')

In [134]:
import zipfile
import os

# Define the files to be packaged and the compressed file name. 
files_to_zip = ['submission_model.py', 'submission_dic.pth']
zip_filename = 'submission.zip'

# Create a zip file to submit.
with zipfile.ZipFile(zip_filename, 'w') as zipf:
    for file in files_to_zip:
        # Add files to the zip file
        zipf.write(file, os.path.basename(file))

print(f'{zip_filename} is created successfully!')

submission.zip is created successfully!